%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\arsha_000\OneDrive\DS_Uni_15-16\Visual Analytics\Coursework2\mmscaled_group_country_merged.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/07 19:41:44

%% Import the data
[~, ~, raw] = xlsread('C:\Users\arsha_000\OneDrive\DS_Uni_15-16\Visual Analytics\Coursework2\mmscaled_group_country_merged.xlsx','Sheet1','C2:L215');

%% Create output variable
feat = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;