function createfigure(yvector1, yvector2, yvector3, yvector4, yvector5, yvector6)
%CREATEFIGURE(YVECTOR1, YVECTOR2, YVECTOR3, YVECTOR4, YVECTOR5, YVECTOR6)
%  YVECTOR1:  bar yvector
%  YVECTOR2:  bar yvector
%  YVECTOR3:  bar yvector
%  YVECTOR4:  bar yvector
%  YVECTOR5:  bar yvector
%  YVECTOR6:  bar yvector

%  Auto-generated by MATLAB on 07-Apr-2016 20:50:48

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create bar
bar1 = bar(yvector1,'Parent',subplot1,'ShowBaseLine','off',...
    'Horizontal','on',...
    'EdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'BarWidth',1);
baseline1 = get(bar1,'BaseLine');
set(baseline1,'Visible','off');

% Create xlabel
xlabel('Silhouette Value','FontSize',7.7);

% Create title
title('Kmeans with k=2','FontSize',8);

% Create ylabel
ylabel('Cluster','FontSize',7.7);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[-Inf 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[1 226]);
box(subplot1,'on');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'FontSize',7,'YTick',[109 220],'YTickLabel',{'1','2'});
% Create subplot
subplot2 = subplot(3,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create bar
bar(yvector2,'Parent',subplot2,'Horizontal','on',...
    'EdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'BarWidth',1);

% Create xlabel
xlabel('Silhouette Value','FontSize',7.7);

% Create title
title('Kmeans with k=3','FontSize',8);

% Create ylabel
ylabel('Cluster','FontSize',7.7);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[1 230]);
box(subplot2,'on');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'FontSize',7,'YTick',[10 118.5 224],'YTickLabel',{'1','2','3'});
% Create subplot
subplot3 = subplot(3,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create bar
bar2 = bar(yvector3,'Parent',subplot3,'ShowBaseLine','off',...
    'Horizontal','on',...
    'EdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'BarWidth',1);
baseline2 = get(bar2,'BaseLine');
set(baseline2,'Visible','off');

% Create xlabel
xlabel('Silhouette Value','FontSize',7.7);

% Create title
title('Kmeans with k=5','FontSize',8);

% Create ylabel
ylabel('Cluster','FontSize',7.7);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[1 238]);
box(subplot3,'on');
axis(subplot3,'ij');
% Set the remaining axes properties
set(subplot3,'FontSize',7,'YTick',[94.5 191 202.5 212 225.5],'YTickLabel',...
    {'1','2','3','4','5'});
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.568948151430742 0.409632352941176 0.334659090909091 0.215735294117647]);
hold(axes1,'on');

% Create bar
bar3 = bar(yvector4,'Parent',axes1,'ShowBaseLine','off','Horizontal','on',...
    'EdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'BarWidth',1);
baseline3 = get(bar3,'BaseLine');
set(baseline3,'Visible','off');

% Create xlabel
xlabel('Silhouette Value','FontSize',7.7);

% Create title
title('Kmeans with k=7','FontSize',8);

% Create ylabel
ylabel('Cluster','FontSize',7.7);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 246]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'FontSize',7,'YTick',[94.5 189.5 195 203 219.5 234 241],...
    'YTickLabel',{'1','2','3','4','5','6','7'});
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.132785515320334 0.0543657331136738 0.334659090909091 0.269722114545983]);
hold(axes2,'on');

% Create bar
bar4 = bar(yvector5,'Parent',axes2,'ShowBaseLine','off','Horizontal','on',...
    'EdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'BarWidth',1);
baseline4 = get(bar4,'BaseLine');
set(baseline4,'Visible','off');

% Create xlabel
xlabel('Silhouette Value','FontSize',5.5);

% Create title
title('Kmeans with k=9','FontSize',8);

% Create ylabel
ylabel('Cluster','FontSize',5.5);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[1 254]);
box(axes2,'on');
axis(axes2,'ij');
% Set the remaining axes properties
set(axes2,'FontSize',5,'YTick',...
    [90 181 188.5 200.5 212 224.5 236.5 243.5 250],'YTickLabel',...
    {'1','2','3','4','5','6','7','8','9'});
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.570340909090909 0.0543657331136738 0.334659090909091 0.271369561003973]);
hold(axes3,'on');

% Create bar
bar5 = bar(yvector6,'Parent',axes3,'ShowBaseLine','off','Horizontal','on',...
    'EdgeColor',[0.635294139385223 0.0784313753247261 0.184313729405403],...
    'BarWidth',1);
baseline5 = get(bar5,'BaseLine');
set(baseline5,'Visible','off');

% Create xlabel
xlabel('Silhouette Value','FontSize',5.5);

% Create title
title('Kmeans with k=11','FontSize',8);

% Create ylabel
ylabel('Cluster','FontSize',5.5);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 1.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[1 262]);
box(axes3,'on');
axis(axes3,'ij');
% Set the remaining axes properties
set(axes3,'FontSize',5,'YTick',...
    [5 95.5 186.5 192.5 199 208.5 223 236 244.5 251 257],'YTickLabel',...
    {'1','2','3','4','5','6','7','8','9','10','11'});
